//
// Created by ivan on 28.04.17.
//

#ifndef MINI_JAVA_COMPILATOR_CONTROLFLOWGRAPHBUILDER_H
#define MINI_JAVA_COMPILATOR_CONTROLFLOWGRAPHBUILDER_H



class ControlFlowGraphBuilder {

};



#endif //MINI_JAVA_COMPILATOR_CONTROLFLOWGRAPHBUILDER_H
