//
// Created by ivan on 22.04.17.
//

#ifndef MINI_JAVA_COMPILATOR_CCALLSIMPLIFIERVISITOR_H
#define MINI_JAVA_COMPILATOR_CCALLSIMPLIFIERVISITOR_H

#endif //MINI_JAVA_COMPILATOR_CCALLSIMPLIFIERVISITOR_H
